services:
  todo-app:
    image: node:21
    container_name: todo-app
    volumes:
      - ./app:/app
    working_dir: /app
    user: "${USER_ID}:${GROUP_ID}"
    tty: true
    ports:
      - "3000:3000"
